version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - terraform/install:
          terraform_version: '1.2.3'
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .

workflows:
  example-workflow:
    jobs:
      - example-job
